### ISSUE TITLE
[Enhancement] CI/CD

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/tooling#11]
## Description

As a product owner, I want to use CI/CD to establish regular testing and building of code, so it is done in an automated and consistent way. Therefore we need to evaluate and document a solution and provide some guidance (template repository) for the same.

## Criteria

- solution evaluated
- template repo updated with example code
- integration in github (visible in PR, shields)
- nice-to-have: local reproduction possible
- nice-to-have: own workers can be added
- free for public/open source repositories

## Additional information

The short list for now:

- travis-ci
- cirrus-ci
- github-actions

**Comment by daniel-schier** [comment]
cirrus-ci seems to have a nice approach.

it is free, fast, can be tested locally and is really easy to understand.
