### ISSUE TITLE
[Enhancement] Docker Hub integration

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/tooling#12]
## Description

As a product owner, I want to provide container images on Docker Hub, too. Therefore we need to have a properly setup integration and docker hub organization.

## Criteria

- organization created and linked (mail from @dschier-wtd)
- test container repository created and tested
- build is either done via ci/cd (see #11) or in Docker itself

## Additional information

- https://docs.docker.com/docker-hub/builds/link-source/

**Comment by daniel-schier** [comment]
organization created, slack integration seems broken: https://hub.docker.com/u/whiletruedoio
