### ISSUE TITLE
[Enhancement] Documentation Git

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/tooling#16]
## Description

At while-true-do.io, we are using git. This is mostly well known, but we should document and link some documentation for new contributors, so we have a consistent Git usage.

## Criteria

- file docs/GIT.md created
- creating repo from template documented
- ssh key generation and adding to GitHub documented
- meaningful commit messages documented (see .gitmessage file)
- meaning of .gitignore and .gitattributes documented)
- signing commits documented

## Additional information

- https://blog.while-true-do.io/git-getting-started/
- https://blog.while-true-do.io/git-next-steps/

Also check out the files .gitignore, .gitattributes and .gitmessage for links to upstream docs.

**Comment by daniel-schier** [comment]
The minimal development process should be documented, too. It should also point to the Contribution guide, where this is already documented with some bullet points.
