### ISSUE TITLE
[Enhancement] docker hub -> slack integration

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/tooling#18]
## Description

As a product owner, I want to enable developers to see new docker image releases in slack, too. There is an option to enable this, provided by docker hub.

## Criteria

- failed releases notify the #developer channel in slack
- succesfull releases notify #developer channel in slack
- integration is documented

## Additional information

- currently this functionality is broken and followed up by a support request from @dschier-wtd

**Comment by pdq21** [comment]
[Docker Hub / Manuals / Set up a Slack integration](https://docs.docker.com/docker-hub/slack_integration/)
Account Settings - Notifications - Select Channel - Authorize - Select Notification Level
- Off
- Only Failures
- Everything

**Comment by daniel-schier** [comment]
This does not work and I have a bugreport open at Docker.

**Comment by daniel-schier** [comment]
obsolete
