### ISSUE TITLE
[Enhancement] Evaluate static code scan utilities

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/tooling#21]
## Description

GitHub offers a couple of apps for static code analysis. We already had a look at codacy and code climate (both are not configurable via dotfile). We may have another look at some.

## Criteria

- must be free for opensource/public
- support common linters and check tools
- at least supports yamllint, markdownlint, shellcheck
- optional supports kubernetes, docker, ansible, js linters/scanners
- optional checks for published secrets
- is well-supported

## Deliverable

- documentation
- demo implementation in a repository

## Additional information

- https://github.com/marketplace/semgrep-dev
- https://github.com/marketplace/lgtm
- https://github.com/marketplace/snyk
- https://github.com/marketplace/sonarcloud

**Comment by daniel-schier** [comment]
codefactor seems very promising.

**Comment by daniel-schier** [comment]
testing code-factor extensively. really promising.

**Comment by daniel-schier** [comment]
all repos now in codefactor https://www.codefactor.io/dashboard. the shield needs to be added to some.

**Comment by daniel-schier** [comment]
done
