### ISSUE TITLE
[Enhancement] evaluate gitter.im for a combined slack+irc alternative

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/tooling#22]
## Description

Currently, we need multiple accounts to communicate with the community (IRC+slack). Furthermore, Slack has some "flaws" when it comes to open communities. I just had a short look at gitter.im, which seems to offer a nice package as listed below:

- clients for win/mac/linux
- integration in github
- logins without special registration, but github/gitlab/bitbucket
- embedable chat for websites
- irc bridge

## Criteria

- evaluate if it may work for us
- test if integration options for the below list are exiting
  - notify github events (new ticket, pull request)
  - notify for twitter messages
  - notify for ghost blog messages
  - irc bridge to another network
- private channels
- voice/audio chat
- markdown in chat
- overall experience

**Comment by daniel-schier** [comment]
Gitter is out. Instead, I have added matrix channels. In the future, we can also think about a dedicated instance under the while-true-do.io domain.

Channels as below:

```
space: #whiletruedoio:matrix.org
channel: #whiletruedoio-community:matrix.org
channel: #whiletruedoio-development:matrix.org
channel: #whiletruedoio-infrastructure:matrix.org
channel: #whiletruedoio-random:matrix.org
```

I will document the same accordingly and remove the slack space afterwards.

**Comment by daniel-schier** [comment]
channels done and published via .github repository.
