### ISSUE TITLE
Enhancement: monitoring integration

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/tooling#8]
As a product owner, I want to monitor running services and integrate alerts into our existing stack, so users will get information as soon as possible.

AC:

- running services can be monitored
- hosts can be monitored
- free for open source
- integrations for slack and mail existing
- optional: statuspage

Deliverable:

- monitoring document created
- integrations explained and created

**Comment by daniel-schier** [comment]
Providing some alerts to twitter is also a nice addition
